# Generated by Django 6.0.5 on 2026-05-26 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_admission', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('URGENCE', 'Urgence'), ('TRANSFERT', 'Transfert')], default='PROGRAMMEE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SORTI', 'Sorti'), ('TRANSFERE', 'Transféré'), ('DECEDE', 'Décédé')], default='EN_COURS', max_length=20)),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('date_previsionnelle_sortie', models.DateField(blank=True, null=True)),
                ('motif_hospitalisation', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('lit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_structure.lit')),
                ('medecin_referent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_suivies', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_structure.servicehospitalier')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame'), ('MLLE', 'Mademoiselle')], default='M', max_length=4)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('numero_identite_national', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('numero_securite_sociale', models.CharField(blank=True, max_length=50)),
                ('numero_dossier', models.CharField(editable=False, max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField()),
                ('personne_a_prevenir', models.CharField(blank=True, max_length=200)),
                ('telephone_urgence', models.CharField(blank=True, max_length=20)),
                ('mutuelle', models.CharField(blank=True, max_length=100)),
                ('numero_affiliation', models.CharField(blank=True, max_length=50)),
                ('consentement_donnees', models.BooleanField(default=False)),
                ('consentement_recherche', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField()),
                ('diagnostic', models.TextField(blank=True)),
                ('diagnostic_cim10', models.CharField(blank=True, help_text='Code CIM-10', max_length=20)),
                ('traitement_prescrit', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True)),
                ('est_terminee', models.BooleanField(default=False)),
                ('signature_electronique', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.admission')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_realisees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_structure.servicehospitalier')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='clinical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ConstanteVitale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('tension_arterielle', models.CharField(blank=True, max_length=20)),
                ('frequence_cardiaque', models.IntegerField(blank=True, null=True)),
                ('frequence_respiratoire', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('saturation_o2', models.IntegerField(blank=True, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('autres', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='clinical.admission')),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes_saisies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='clinical.patient')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='clinical.patient'),
        ),
    ]
