# Generated by Django 6.0.5 on 2026-06-03 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('hospital_structure', '0002_lit_patient_actuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'EN_COURS')), fields=('patient',), name='unique_admission_active_par_patient'),
        ),
    ]
