# Generated by Django 6.0.3 on 2026-06-18 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_merge_20260618'),
        ('prescriptions', '0002_prescription_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('frequence', models.CharField(blank=True, help_text='Ex: 3x/jour, matin et soir', max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_soins', to='clinical.admission')),
                ('infirmier_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_soins_assignes', to=settings.AUTH_USER_MODEL)),
                ('medecin_prescripteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_soins_prescrits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_soins', to='clinical.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_soins', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
