# Generated by Django 6.0.5 on 2026-05-26 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('laboratory', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('taux_prise_en_charge', models.IntegerField(default=70, help_text='Pourcentage pris en charge (ex: 70%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(editable=False, max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PARTIELLE', 'Payée partiellement'), ('PAYEE', 'Payée totalement'), ('IMPAYEE', 'Impayée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_patient', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_restant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clinical.admission')),
                ('emise_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_emises', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clinical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('NUITEE', 'Nuitée'), ('CONSULTATION', 'Consultation'), ('EXAMEN', 'Examen'), ('MEDICAMENT', 'Médicament'), ('CONSOMMABLE', 'Consommable'), ('ACTE', 'Acte médical')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.admission')),
                ('demande_examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.demandeexamen')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='billing.facture')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prescriptions.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PriseEnChargeAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=True)),
                ('assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.assurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='clinical.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money'), ('VIRAMENT', 'Virement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20)),
                ('operateur', models.CharField(blank=True, max_length=10)),
                ('numero_telephone', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='ID transaction opérateur', max_length=100)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='billing.facture')),
            ],
        ),
    ]
