# Generated by Django 6.0.5 on 2026-06-03 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('EMISSION', 'Émission facture'), ('TIERS_PAYANT', 'Tiers-payant assurance'), ('PAIEMENT', 'Paiement reçu'), ('AJUSTEMENT', 'Ajustement'), ('ANNULATION', 'Annulation')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hash_signature', models.CharField(max_length=128, unique=True)),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal', to='billing.facture')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'ordering': ['timestamp'],
            },
        ),
    ]
