# Generated by Django 6.0.5 on 2026-05-26 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('HEMATOLOGIE', 'Hématologie'), ('BIOCHIMIE', 'Biochimie'), ('MICROBIOLOGIE', 'Microbiologie'), ('IMMUNOLOGIE', 'Immunologie'), ('ANATOMOPATHOLOGIE', 'Anatomopathologie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duree_traitement_heures', models.IntegerField(default=24, help_text='Délai moyen de rendu')),
                ('jeun_requis', models.BooleanField(default=False)),
                ('instructions_prelevement', models.TextField(blank=True)),
                ('valeurs_normales', models.TextField(blank=True, help_text='Description des valeurs de référence')),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PRESCRIT', 'Prescrit'), ('PRELEVE', 'Prélevé'), ('EN_COURS', "En cours d'analyse"), ('VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='PRESCRIT', max_length=20)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('urgence', models.BooleanField(default=False)),
                ('notes_prescripteur', models.TextField(blank=True)),
                ('date_prelevement', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_examens', to='clinical.consultation')),
                ('medecin_prescripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_prescrits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_examens', to='clinical.patient')),
                ('preleve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prelevements', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_examens', to=settings.AUTH_USER_MODEL)),
                ('examen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='laboratory.examentype')),
            ],
        ),
        migrations.CreateModel(
            name='Prelevement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_prelevement', models.CharField(choices=[('SANG', 'Prise de sang'), ('URINE', 'Urines'), ('SELLES', 'Selles'), ('ECOUVILLON', 'Ecouvillon'), ('BIOPSIE', 'Biopsie'), ('AUTRE', 'Autre')], default='SANG', max_length=20)),
                ('date_prelevement', models.DateTimeField(auto_now_add=True)),
                ('tube_type', models.CharField(blank=True, max_length=100)),
                ('quantite', models.CharField(blank=True, max_length=50)),
                ('conditions', models.TextField(blank=True, help_text='Conditions de transport/conservation')),
                ('commentaire', models.TextField(blank=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prelevement', to='laboratory.demandeexamen')),
                ('preleve_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prelevements_effectues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('resultats', models.TextField(help_text="Résultats détaillés de l'examen")),
                ('interpretation', models.TextField(blank=True, help_text='Interprétation clinique')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='resultats_lab/')),
                ('est_valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('signature_electronique', models.TextField(blank=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='laboratory.demandeexamen')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_saisis', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_valides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
