# Generated by Django 6.0.5 on 2026-06-03 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexamen',
            name='affecte_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_affectes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='date_affectation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultatexamen',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resultatexamen',
            name='est_publie',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoriqueModificationResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anciens_resultats', models.TextField()),
                ('nouveaux_resultats', models.TextField()),
                ('ancienne_interpretation', models.TextField(blank=True)),
                ('nouvelle_interpretation', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='laboratory.resultatexamen')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
