# Generated by Django 6.0.5 on 2026-05-26 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_structure', '0002_lit_patient_actuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_personnel', models.CharField(choices=[('MEDECIN', 'Médecin'), ('INFIRMIER', 'Infirmier'), ('BIOLOGISTE', 'Biologiste'), ('PHARMACIEN', 'Pharmacien'), ('SECRETAIRE', 'Secrétaire'), ('ADMINISTRATIF', 'Administratif'), ('TECHNICIEN', 'Technicien de laboratoire'), ('AUTRE', 'Autre')], max_length=20)),
                ('statut_emploi', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGIAIRE', 'Stagiaire'), ('VACATAIRE', 'Vacataire'), ('CONSULTANT', 'Consultant')], default='CDI', max_length=20)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('fonction', models.CharField(blank=True, max_length=200)),
                ('specialite', models.CharField(blank=True, help_text='Pour les médecins: Cardiologue, Pédiatre...', max_length=200)),
                ('telephone_pro', models.CharField(blank=True, max_length=20)),
                ('email_pro', models.EmailField(blank=True, max_length=254)),
                ('bureau', models.CharField(blank=True, max_length=100)),
                ('date_embauche', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('diplomes', models.TextField(blank=True)),
                ('num_ordre_medecins', models.CharField(blank=True, max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnels', to='hospital_structure.servicehospitalier')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé annuel'), ('MALADIE', 'Arrêt maladie'), ('SANS_SOLDE', 'Congé sans solde'), ('MATERNITE', 'Congé maternité'), ('EVENEMENT', 'Congé événement familial')], max_length=20)),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='ATTENTE', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_jours', models.IntegerField(editable=False)),
                ('motif', models.TextField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='conges/')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True)),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_demandes', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='rh.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_garde', models.CharField(choices=[('JOUR', 'Garde de jour (8h-20h)'), ('NUIT', 'Garde de nuit (20h-8h)'), ('24H', 'Garde de 24h'), ('ASTREINTE', 'Astreinte'), ('PERMANENCE', 'Permanence')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('est_effectuee', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('date_planification', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardes', to='rh.personnel')),
                ('planifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardes_planifiees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardes', to='hospital_structure.servicehospitalier')),
            ],
            options={
                'verbose_name': 'Planning de garde',
                'verbose_name_plural': 'Plannings de gardes',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_a_payer', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('nb_heures_sup', models.IntegerField(default=0)),
                ('montant_heures_sup', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('details', models.JSONField(default=dict, help_text='Détail des primes et déductions')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='fiches_paie/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('generee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to='rh.personnel')),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': {('personnel', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('CONGE', 'Congé'), ('MALADIE', 'Arrêt maladie'), ('FORMATION', 'Formation'), ('RETARD', 'Retard')], default='PRESENT', max_length=20)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='presences/')),
                ('commentaire', models.TextField(blank=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='rh.personnel')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('personnel', 'date')},
            },
        ),
    ]
