# Generated by Django 6.0.3 on 2026-07-09 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.EmailField(db_index=True, max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('type_email', models.CharField(choices=[('OTP_LOGIN', 'OTP - Connexion'), ('RDV_CONFIRMATION', 'RDV - Confirmation'), ('RDV_REMINDER', 'RDV - Rappel 24h'), ('EXAM_PUBLISHED', 'Exam - Résultats publiés'), ('PATIENT_REGISTRATION', 'Inscription - Bienvenue'), ('PRESCRIPTION_VALIDATED', 'Prescription validée'), ('DISCHARGE_NOTIFICATION', 'Sortie hospitalière'), ('INVOICE_CREATED', 'Facture créée'), ('MEDICATION_REMINDER', 'Rappel médicament'), ('DOCTOR_ALERT', 'Alerte médecin'), ('OTHER', 'Autre')], default='OTHER', max_length=50)),
                ('contenu_plain', models.TextField()),
                ('contenu_html', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('REBOND', 'Rebond'), ('SPAM', 'Marqué spam')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('erreur_message', models.TextField(blank=True)),
                ('uuid_message', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tentative_num', models.PositiveSmallIntegerField(default=0)),
                ('max_tentatives', models.PositiveSmallIntegerField(default=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('ip_origine', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RenameIndex(
            model_name='upload',
            new_name='common_uplo_hash_sh_9a0ccb_idx',
            old_name='common_uplo_hash_s_idx',
        ),
        migrations.RenameIndex(
            model_name='upload',
            new_name='common_uplo_uploade_315f69_idx',
            old_name='common_uplo_uploade__idx',
        ),
        migrations.RenameIndex(
            model_name='upload',
            new_name='common_uplo_contenu_589a38_idx',
            old_name='common_uplo_contenu__idx',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['destinataire', '-date_creation'], name='common_emai_destina_d56605_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['utilisateur', '-date_creation'], name='common_emai_utilisa_71ae40_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['type_email', 'statut'], name='common_emai_type_em_4f536c_idx'),
        ),
    ]
