# Generated by Django 6.0.5 on 2026-05-26 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=100, unique=True)),
                ('quantite_initiale', models.IntegerField()),
                ('quantite_restante', models.IntegerField()),
                ('date_fabrication', models.DateField()),
                ('date_peremption', models.DateField()),
                ('date_reception', models.DateField(auto_now_add=True)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='prescriptions.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('RUPTURE', 'Rupture de stock'), ('SEUIL', "Seuil d'alerte atteint"), ('PEREMPTION', 'Lot proche de péremption')], max_length=20)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('est_resolue', models.BooleanField(default=False)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='prescriptions.medicament')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='pharmacy.lot')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (réception)'), ('SORTIE', 'Sortie (consommation)'), ('PERTE', 'Perte (péremption/casse)'), ('RETOUR', 'Retour fournisseur'), ('AJUSTEMENT', 'Ajustement inventaire')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text='Prescription ID, Bon de commande, etc.', max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='pharmacy.lot')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='prescriptions.medicament')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_totale', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=10)),
                ('medicament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='prescriptions.medicament')),
            ],
        ),
    ]
