# Generated by Django 6.0.5 on 2026-05-26 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_kpi', models.CharField(choices=[('OCCUPATION', "Taux d'occupation des lits"), ('RECETTES_JOUR', 'Recettes du jour'), ('RECETTES_MOIS', 'Recettes du mois'), ('PATIENTS_JOUR', "Patients admis aujourd'hui"), ('EXAMENS_ATTENTE', 'Examens en attente de validation'), ('URGENCES', 'Patients aux urgences'), ('PRESCRIPTIONS_JOUR', 'Prescriptions du jour')], max_length=50, unique=True)),
                ('valeur', models.TextField()),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'KPI en cache',
                'verbose_name_plural': 'KPIs en cache',
            },
        ),
        migrations.CreateModel(
            name='StatistiqueJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('nb_admissions', models.IntegerField(default=0)),
                ('nb_sorties', models.IntegerField(default=0)),
                ('nb_consultations', models.IntegerField(default=0)),
                ('nb_examens_prescrits', models.IntegerField(default=0)),
                ('nb_examens_realises', models.IntegerField(default=0)),
                ('nb_examens_valides', models.IntegerField(default=0)),
                ('nb_prescriptions', models.IntegerField(default=0)),
                ('montant_total_factures', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_encaisse', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_assurance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_occupation_lits', models.FloatField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique journalière',
                'verbose_name_plural': 'Statistiques journalières',
            },
        ),
        migrations.CreateModel(
            name='AlertSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='INFO', max_length=20)),
                ('categorie', models.CharField(choices=[('STOCK', 'Stock pharmacie'), ('PEREMPTION', 'Péremption'), ('FINANCE', 'Finance'), ('LABORATOIRE', 'Laboratoire'), ('RH', 'Ressources humaines'), ('SYSTEME', 'Système')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('est_resolue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('resolution_commentaire', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation', 'niveau'],
            },
        ),
    ]
