# Generated by Django 6.0.5 on 2026-05-26 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LignePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prescitee', models.IntegerField()),
                ('quantite_administree', models.IntegerField(default=0)),
                ('frequence', models.CharField(help_text='ex: 2x par jour', max_length=100)),
                ('duree_jours', models.IntegerField(default=1)),
                ('instructions_specifiques', models.TextField(blank=True)),
                ('doses_omises', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('forme', models.CharField(choices=[('COMPRIME', 'Comprimé'), ('INJECTION', 'Injection'), ('SIROP', 'Sirop'), ('POMMADE', 'Pommade'), ('PERFUSION', 'Perfusion'), ('GOUTTES', 'Gouttes')], default='COMPRIME', max_length=20)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('unite', models.CharField(default='mg', max_length=20)),
                ('fabricant', models.CharField(blank=True, max_length=200)),
                ('est_generique', models.BooleanField(default=False)),
                ('est_sur_ordonnance', models.BooleanField(default=True)),
                ('est_remboursable', models.BooleanField(default=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrationMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administration', models.DateTimeField(auto_now_add=True)),
                ('quantite_administree', models.IntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('est_refuse', models.BooleanField(default=False)),
                ('reaction_indesirable', models.TextField(blank=True)),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to=settings.AUTH_USER_MODEL)),
                ('ligne_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='prescriptions.ligneprescription')),
            ],
        ),
        migrations.AddField(
            model_name='ligneprescription',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.medicament'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validée'), ('ADMINISTREE', 'Administrée'), ('PARTIELLE', 'Partiellement administrée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('est_verrouillee', models.BooleanField(default=False)),
                ('signature_electronique', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.consultation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_emises', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.patient')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ligneprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='prescriptions.prescription'),
        ),
    ]
