# Generated by Django 6.0.5 on 2026-06-03 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteDoseOmise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('est_traitee', models.BooleanField(default=False)),
                ('ligne_prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_doses', to='prescriptions.ligneprescription')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_doses_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_alerte'],
            },
        ),
    ]
