# Generated by Django 6.0.5 on 2026-05-26 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('adresse', models.TextField(blank=True)),
                ('nombre_etages', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHospitalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type_service', models.CharField(choices=[('MEDICAL', 'Service Médical'), ('CHIRURGICAL', 'Service Chirurgical'), ('TECHNIQUE', 'Plateau Technique'), ('ADMINISTRATIF', 'Service Administratif')], default='MEDICAL', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('etage', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hospital_structure.batiment')),
                ('chef_de_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('type_chambre', models.CharField(choices=[('INDIVIDUELLE', 'Individuelle'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('SALLE_COMMUNE', 'Salle Commune'), ('REANIMATION', 'Réanimation'), ('ISOLEMENT', 'Isolement')], default='DOUBLE', max_length=20)),
                ('capacite_max', models.IntegerField(default=2)),
                ('prix_par_jour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('a_baignoire', models.BooleanField(default=False)),
                ('a_telephone', models.BooleanField(default=False)),
                ('a_television', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='hospital_structure.servicehospitalier')),
            ],
            options={
                'unique_together': {('service', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('statut', models.CharField(choices=[('LIBRE', 'Libre'), ('OCCUPE', 'Occupé'), ('RESERVE', 'Réservé'), ('HORS_SERVICE', 'Hors Service')], default='LIBRE', max_length=20)),
                ('est_medicalise', models.BooleanField(default=False)),
                ('hauteur_reglable', models.BooleanField(default=False)),
                ('barriere_laterale', models.BooleanField(default=True)),
                ('date_dernier_changement', models.DateField(blank=True, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='hospital_structure.chambre')),
            ],
            options={
                'unique_together': {('chambre', 'numero')},
            },
        ),
    ]
