# Generated by Django 6.0.5 on 2026-05-26 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('hospital_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lit',
            name='patient_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lit_occupe', to='clinical.patient'),
        ),
    ]
