# Generated by Django 6.0.5 on 2026-05-26 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.IntegerField()),
                ('patient_nom', models.CharField(max_length=200)),
                ('medecin_nom', models.CharField(max_length=200)),
                ('date_consultation', models.DateTimeField()),
                ('action', models.CharField(max_length=50)),
                ('utilisateur', models.CharField(max_length=150)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('READ', 'Lecture'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('VALIDATE', 'Validation'), ('EXPORT', 'Export'), ('PRINT', 'Impression'), ('SIGN', 'Signature')], max_length=20)),
                ('utilisateur_username', models.CharField(blank=True, max_length=150)),
                ('utilisateur_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('app_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('fields_changed', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('hash_signature', models.CharField(max_length=128, unique=True)),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
