# Generated by Django 6.0.3 on 2026-06-18 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0004_merge_20260618'),
        ('hospital_structure', '0002_lit_patient_actuel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('duree_creneau_minutes', models.PositiveIntegerField(default=30)),
                ('est_actif', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites_medecins', to='hospital_structure.servicehospitalier')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('duree_minutes', models.PositiveIntegerField(default=30)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé'), ('ABSENT', 'Absent')], default='PLANIFIE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('confirmation_email_envoyee', models.BooleanField(default=False)),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_crees', to=settings.AUTH_USER_MODEL)),
                ('disponibilite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.disponibilitemedecin')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_medecin', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='clinical.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_structure.servicehospitalier')),
            ],
            options={
                'ordering': ['date_heure'],
            },
        ),
        migrations.AddIndex(
            model_name='disponibilitemedecin',
            index=models.Index(fields=['medecin', 'date_debut'], name='appointment_medecin_1fa37b_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['patient', 'date_heure'], name='appointment_patient_d9c16f_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['medecin', 'date_heure'], name='appointment_medecin_46c775_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(fields=['statut'], name='appointment_statut_3f4006_idx'),
        ),
    ]
