# Generated by Django 6.0.3 on 2026-06-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCIM10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=500)),
                ('chapitre', models.CharField(blank=True, max_length=200)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Code CIM-10',
                'verbose_name_plural': 'Codes CIM-10',
                'ordering': ['code'],
            },
        ),
    ]
