# Generated by Django 6.0.3 on 2026-06-18 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('plateforme', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='ANDROID', max_length=10)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_usage', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('RDV', 'Rendez-vous'), ('MEDICAMENT', 'Rappel médicament'), ('RESULTAT', 'Résultat laboratoire'), ('MESSAGE', 'Message'), ('GENERAL', 'Général')], default='GENERAL', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('est_lue', models.BooleanField(default=False)),
                ('push_envoyee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
